---
title: "How Speed Affects Offensive Ability"
author: "Kyle Sabo"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

```{r, include=FALSE}
speedData <- read.csv("sprint_speed2021.csv")
hittingData <- read.csv("expected_stats2021.csv")
rawData <- full_join(hittingData, speedData, by = "player_id")
rawData2021 <- rawData %>%
  rename(woba_diff = est_woba_minus_woba_diff, 
         ba_diff = est_ba_minus_ba_diff, 
         slg_diff = est_slg_minus_slg_diff) %>%
  mutate(year = 2021) %>%
  select(player_id, woba_diff, ba_diff, slg_diff, sprint_speed, year) %>% 
  drop_na()
rawData2021


speedData <- read.csv("sprint_speed2020.csv")
hittingData <- read.csv("expected_stats2020.csv")
rawData <- full_join(hittingData, speedData, by = "player_id")
rawData2020 <- rawData %>%
  rename(woba_diff = est_woba_minus_woba_diff, 
         ba_diff = est_ba_minus_ba_diff, 
         slg_diff = est_slg_minus_slg_diff) %>%
  mutate(year = 2020) %>%
  select(player_id, woba_diff, ba_diff, slg_diff, sprint_speed, year) %>% 
  drop_na()
rawData2020


speedData <- read.csv("sprint_speed2019.csv")
hittingData <- read.csv("expected_stats2019.csv")
rawData <- full_join(hittingData, speedData, by = "player_id")
rawData2019 <- rawData %>%
  rename(woba_diff = est_woba_minus_woba_diff, 
         ba_diff = est_ba_minus_ba_diff, 
         slg_diff = est_slg_minus_slg_diff) %>%
  mutate(year = 2019) %>%
  select(player_id, woba_diff, ba_diff, slg_diff, sprint_speed, year) %>% 
  drop_na()
rawData2019


speedData <- read.csv("sprint_speed2018.csv")
hittingData <- read.csv("expected_stats2018.csv")
rawData <- full_join(hittingData, speedData, by = "player_id")
rawData2018 <- rawData %>%
  rename(woba_diff = est_woba_minus_woba_diff, 
         ba_diff = est_ba_minus_ba_diff, 
         slg_diff = est_slg_minus_slg_diff) %>%
  mutate(year = 2018) %>%
  select(player_id, woba_diff, ba_diff, slg_diff, sprint_speed, year) %>%  
  drop_na()
rawData2018

speedData <- read.csv("sprint_speed2017.csv")
hittingData <- read.csv("expected_stats2017.csv")
rawData <- full_join(hittingData, speedData, by = "player_id")
rawData2017 <- rawData %>%
  rename(woba_diff = est_woba_minus_woba_diff, 
         ba_diff = est_ba_minus_ba_diff, 
         slg_diff = est_slg_minus_slg_diff) %>%
  mutate(year = 2017) %>%
  select(player_id, woba_diff, ba_diff, slg_diff, sprint_speed, year) %>% 
  drop_na()
rawData2017

speedData <- read.csv("sprint_speed2016.csv")
hittingData <- read.csv("expected_stats2016.csv")
rawData <- full_join(hittingData, speedData, by = "player_id")
rawData2016 <- rawData %>%
  rename(woba_diff = est_woba_minus_woba_diff, 
         ba_diff = est_ba_minus_ba_diff, 
         slg_diff = est_slg_minus_slg_diff) %>%
  mutate(year = 2016) %>%
  select(player_id, woba_diff, ba_diff, slg_diff, sprint_speed, year) %>% 
  drop_na()
rawData2016

speedData <- read.csv("sprint_speed2015.csv")
hittingData <- read.csv("expected_stats2015.csv")
rawData <- full_join(hittingData, speedData, by = "player_id")
rawData2015 <- rawData %>%
  rename(woba_diff = est_woba_minus_woba_diff, 
         ba_diff = est_ba_minus_ba_diff, 
         slg_diff = est_slg_minus_slg_diff) %>%
  mutate(year = 2015) %>%
  select(player_id, woba_diff, ba_diff, slg_diff, sprint_speed, year) %>%  
  drop_na()
rawData2015

totalData <- rbind(rawData2015,rawData2016,rawData2017,rawData2018,rawData2019,rawData2020,rawData2021)
```

```{r}
ggplot(data = totalData, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red") +
  labs(title = "2015-2021 Sprint Speed vs xwOBA difference",
       subtitle = "The faster a player is, the more likely they outperform their 'expected' hitting.",
       x = "Sprint Speed (m/s)",
       y = "xwOBA difference (positive means they 'overperformed')",
       caption = "Source: baseballsavant.mlb.com")
ggplot(data = totalData, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red") +
  labs(title = "2015-2021 Sprint Speed vs xBA difference",
       subtitle = "The faster a player is, the more likely they outperform their 'expected' hitting.",
       x = "Sprint Speed (m/s)",
       y = "xBA difference (positive means they 'overperformed')",
       caption = "Source: baseballsavant.mlb.com")
ggplot(data = totalData, 
       mapping = aes(x = sprint_speed, y = slg_diff)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red") +
  labs(title = "2015-2021 Sprint Speed vs xSLG difference",
       subtitle = "The faster a player is, the more likely they outperform their 'expected' hitting.",
       x = "Sprint Speed (m/s)",
       y = "xSLG difference (positive means they 'overperformed')",
       caption = "Source: baseballsavant.mlb.com")
```

```{r}
ggplot(data = rawData2021, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red") +
  labs(title = "2021 Sprint Speed vs xwOBA difference",
       subtitle = "The fastest hitters were more unlucky, but above average runners had a higher xwOBA difference.",
       x = "Sprint Speed (m/s)",
       y = "xwOBA difference (positive means 'lucky')",
       caption = "Source: baseballsavant.mlb.com")
ggplot(data = rawData2021, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red") +
  labs(title = "2021 Sprint Speed vs xBA difference",
       subtitle = "The fastest hitters were more unlucky, but above average runners had a higher xwOBA difference.",
       x = "Sprint Speed (m/s)",
       y = "xBA difference (positive means 'lucky')",
       caption = "Source: baseballsavant.mlb.com")
```
```{r}
ggplot(data = rawData2020, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
ggplot(data = rawData2020, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
```

```{r}
ggplot(data = rawData2019, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
ggplot(data = rawData2019, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
```

```{r}
ggplot(data = rawData2018, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
ggplot(data = rawData2018, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
```

```{r}
ggplot(data = rawData2017, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
ggplot(data = rawData2017, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
```

```{r}
ggplot(data = rawData2016, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
ggplot(data = rawData2016, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
```

```{r}
ggplot(data = rawData2015, 
       mapping = aes(x = sprint_speed, y = woba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
ggplot(data = rawData2015, 
       mapping = aes(x = sprint_speed, y = ba_diff)) +
  geom_point() +
  geom_smooth(method = "loess", formula = "y ~ x", color = "red")
```